---
- name: 워커 노드 시스템 정보 수집
  hosts: furiosa_workers
  gather_facts: false
  tasks:
    - name: bc 패키지 설치
      apt:
        name: bc
        state: present
      become: yes

    - name: host_info.sh 전송
      copy:
        src: ../scripts/host_info.sh
        dest: /tmp/host_info.sh
        mode: '0755'

    - name: host_info.sh 실행
      shell: cd /tmp && bash /tmp/host_info.sh
      become: yes
      register: script_output

    - name: 생성된 로그 파일 경로 확인
      shell: ls -t /tmp/*.log | head -1
      register: log_file_path

    - name: 컨트롤 노드 logs 디렉토리 생성
      file:
        path: "{{ lookup('env', 'HOME') }}/logs"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: 로그 파일 컨트롤 노드로 수집
      fetch:
        src: "{{ log_file_path.stdout }}"
        dest: "~/logs/"
        flat: yes
      become: yes

    - name: 워커 노드 임시 파일 정리
      file:
        path: "{{ item }}"
        state: absent
      become: yes
      loop:
        - /tmp/host_info.sh
        - "{{ log_file_path.stdout }}"
